#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to install Nginx

sudo apt-get update
sudo apt_get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
