#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to install Nginx and redirect.

apt-get -y update

apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo sed -i '/server_name _;/a \\n location /redirect_me { \n rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; \n }' /etc/nginx/sites-available/default

service nginx start
