#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to install Nginx and redirect.

sudo apt-get update

sudo apt-get -y install nginx

# Create a new server block configuration
cat > /etc/nginx/sites-available/redirect <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}
EOF

# Enable the new server block configuration
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test the configuration and restart Nginx
nginx -t && systemctl restart nginx
