#!/usr/bin/env bash
# Bash Script that configures a brand new Ubuntu machine to create a custom header.

sudo apt-get update

sudo apt-get install nginx -y

# create a hello world page
echo "Hello World!" | sudo tee /var/www/html/index.html

# create a redirection for our website
sudo sed -i '/server_name _;/a \\n location /redirect_me { \n rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; \n }' /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \n error_page 404 /custom_404.html;\n location = /custom_404.html {\n internal;\n}' /etc/nginx/sites-available/default

# Add custom header configuration to Nginx
sudo sed -i '/server {/a \n add_header X-Served-By '"$hostname"';' /etc/nginx/sites-available/default

# restart the web server after updating the settings
sudo systemctl start nginx
