#!/usr/bin/env bash
# Bash Script that configures a brand new Ubuntu machine to create a custom header.

sudo sed -i "\^http {/a \\tadd_header X-Served-By $hostname;" /etc/nginx/sites-available/default

sudo service nginx restart
