#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to configure HAproxy on the lb-01 server.

# install HAproxy
sudo apt-get update

sudo apt-get install --no-install-recommends software-properties-common -y

sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y

sudo apt-get install haproxy=2.6.\*

# Configure HAproxy so that it send traffic to web-01 and web-02.

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http_front
    bind *:80
    default_backend http_rear

backend http_rear
    balance roundrobin
    server 112925-web-01 100.25.21.206:80 check
    server 112925-web-02 54.84.247.114:80 check

ENABLED=1
EOF

# Start HAproxy service
sudo systemctl start haproxy

sudo systemctl enable haproxy

sudo /etc/init.d/haproxy reload
