#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to configure HAproxy on the lb-01 server.

# install HAproxy
sudo apt-get update

sudo apt-get install --no-install-recommends software-properties-common -y

sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y

sudo apt-get install haproxy=2.6.\*

# Configure HAproxy so that it send traffic to web-01 and web-02.

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend MyFrontend
    bind *:80
    default_backend servers

backend myservers
    balance roundrobin
    server server1 52.87.211.222:80 check
    server server2 54.157.136.112:80 check
EOF

# Start HAproxy service
sudo systemctl start haproxy

sudo systemctl enable haproxy
