#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it

mysqldump -uroot -p"$1" --all-databases | gzip > backup.sql

tar -cvzf "$(date +%Y-%m-%d)".tar.gz backup.sql
