#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it

mysqldump -u root -p tyrell_corp | gzip > backup.sql.gz

tar -cvzf "$(date +%Y-%m-%d)".tar.gz backup.sql.gz
