#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it

MYSQL_USER="root"
MYSQL_PASSWORD="$1"

mysqldump -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" tyrell_corp | gzip > backup.sql.gz

tar -cvzf "$(date +%Y-%m-%d)".tar.gz backup.sql.gz
