#!/usr/bin/env bash
# Script that configures a Nginx server to listen on port 80

sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

PORT=80

NGINX_CONFIG="/etc/nginx/nginx.conf"

sudo sed -i "s/\(^\s*listen\s*\)[0-9]\+/\1$PORT/" "$NGINX_CONFIG"

# Create a symbolic link between /etc/nginx/sites-available/default and /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Ngingx
sudo service nginx restart
