#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

n=0
while [ $n -le 10 ]
do
	echo "To infinity and beyond"
	sleep 2
		echo "I am invincible!!!"
done
