#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.

myapache="apache-access.log"

awk -F " " '{print $1, $9}' $myapache | sort | uniq -c | sort -nr
