#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

h=0

while [ $h -ne 12 ]
do
	echo "Hour: $h"
	m=1
	while [ $m -ne 60 ]
	do
		echo "$m"
		(( m++ ))
	done
	(( h++ ))
done
