#!/usr/bin/env bash
# script that configures Nginx to run as nginx user with limited privileges

sudo service nginx stop

sudo pkill -f apache2

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default

chmod 644 /etc/nginx/nginx.conf

sudo -u nginx service start
