#!/usr/bin/env bash
# script that configures Nginx to run as nginx user with limited privileges

sudo service nginx stop

sudo pkill apache2

useradd -r nginx

sudo sed -i '/^#user www-data/user nginx;' /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx start
